default:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: fireuser
      pass: firepass
      dbname: firedb
      schema: public